API_TOKEN = "8462544144:AAF6C1yUNnbOZ0YzrRfjyq0iDxNsv7Rr25o"
ADMIN_ID = 674187795

SOURCES = {
    "Sostav": "https://www.sostav.ru/rss",
    # "Adindex": "https://adindex.ru/news/news.rss",
    # "РБК": "https://rssexport.rbc.ru/rbcnews/news/30/full.rss",
    # "Ведомости": "https://www.vedomosti.ru/rss/1news",
    "Коммерсант": "https://www.kommersant.ru/RSS/corp.xml",
    "Forbes": "https://www.forbes.ru/newrss.xml",
    "Shoppers": "https://shoppers.media/rss.xml",
    "ТАСС": "https://tass.ru/rss/v2.xml",
    "РИА Новости": "https://ria.ru/export/rss2/archive/index.xml",
    "Известия": "https://iz.ru/xml/rss/all.xml",
}

KEYWORDS = [
    "ритейл",
    "retail",
    "е-ком",
    "e-com",
    "маркетплейс",
    "wildberries",
    "ozon",
    "яндекс маркет",
    "мегамаркет",
    "реклам",
    "интернет-торговл",
    "логистик",
    "склад",
    "лента",
    "магнит",
    "пятерочка",
    "перекресток",
    "вкусвилл",
    "м.видео",
    "эльдорадо",
    "ecommerce",
    "fmcg",
    "fashion",
    "darkstore",
    "даркстор",
    "пвз",
    "курьер",
    "x5",
    "х5",
    "о'кей",
    "озон",
    "wb",
    "rwb",
    "яндекс лавка",
    "самокат",
    "купер",
]
